# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Talvez seja necessario instalar o g++ e/ou o build essentials
      - name: Install g++ compiler and libraries
        run: sudo apt install build-essential
      
      # Runs a single command using the runners shell
      - name: compile
        run: g++ libntpclient.cpp libntpclient.h -o upd_relogio

        # Upload the build artifacts: https://github.com/marketplace/actions/upload-artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: 'file'
          path: '/home/runner/work/hoje/hoje/upd_relogio'
